// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qeczfwvdthkiqorirjae.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFlY3pmd3ZkdGhraXFvcmlyamFlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3MTg4MjMsImV4cCI6MjA3MjI5NDgyM30.3TRz-Eq6h4GBz25vzNUxBrHTPE8t3TELJV0pqTFR2dc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});